DROP TABLE TICKETS;
CREATE TABLE TICKETS (
  ID          BIGSERIAL PRIMARY KEY,
  PROJECT_ID  BIGINT       NOT NULL,
  TITLE       VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(2048),
  PRIORITY    INTEGER DEFAULT 0
);

DROP TABLE LABELS;
CREATE TABLE LABELS (
  TICKET_ID BIGINT,
  LABEL     CHAR(255) NOT NULL
);

DROP TABLE USERS;
CREATE TABLE USERS (
  ID        BIGSERIAL PRIMARY KEY,
  GOOGLE_ID VARCHAR(255),
  EMAIL     VARCHAR(255),
  FULL_NAME VARCHAR(255),
  PICTURE   VARCHAR(2048),
  LOCALE    VARCHAR(16),
  SECURITY_TOKEN VARCHAR(1024)
);

DROP TABLE PROJECTS;
CREATE TABLE PROJECTS (
  ID       BIGSERIAL PRIMARY KEY,
  NAME     VARCHAR(255),
  OWNER_ID BIGINT NOT NULL
);

DROP TABLE USERS_PROJECTS;
CREATE TABLE USERS_PROJECTS (
  USERS_ID    BIGINT NOT NULL,
  PROJECTS_ID BIGINT NOT NULL
);